### ISSUE TITLE
Not able to launch the proto

### ISSUE THREAD

**Issue by christiandjak** [hgwood/falcorception#70]
Hi,
  I've tried to run locally the falcorception. In the client server, i ran npm install; npm start; i've urls displayed in my terminal but nothing is displayed on the server. 
Couldnt have the UI seen in your demo video displayed locally. Any clue on the process to have it work?

**Comment by hgwood** [comment]
You are right. There is a bundling issue with the client code. I don't really understand why but I've managed to work around it and I've pushed a fix. Could you try again ?

**Comment by hgwood** [comment]
By the way, it is normal that the server displays nothing.

**Comment by hgwood** [comment]
Oh and thanks for your interest! :D

**Comment by christiandjak** [comment]
Thanks for the quick answer. I was actually hoping to see UI of the API designer you presented on your video to play with it too. But i have no UI, it is what is expected? I was hoping the have the url http://localhost:3000/src/#/apis/falcorception display me the UI presented in the video. 
May be i didn't get well the scope of the repository. Thanks for the video in devoxx by the way

**Comment by christiandjak** [comment]
We encounter an error when launching the client.... 
Error: _ is not defined
[170]</module.exports</<.resolve.apis@http://localhost:3000/build/bundle.js:65742:1
invoke@http://localhost:3000/build/bundle.js:6159:16

**Comment by hgwood** [comment]
You should get the UI. The error you are getting is the one that I fixed a few days ago. Make sure you have the latest `master` checked out, and do this:
- In one terminal:

```
cd server
npm install
npm start
```
- In another terminal

```
cd client
npm install
npm start
```

The UI should open in a new browser tab automatically. If it doesn't, tell me exactly what happens. Does a browser open with a blank page? Is there any error in the browser console? Is there any errors in the terminals?

**Comment by christiandjak** [comment]
Thanks for the reply. 
In fact i did the process as you adviced, I do have the blank tab which is opening automatically. 
No error is displayed on the terminals. 
Nothing is displayed on the UI, and I have the error in the browser console: 

10:20:00,855 Error: _ is not defined
[170]</module.exports</<.resolve.apis@http://localhost:3000/build/bundle.js:65742:1
invoke@http://localhost:3000/build/bundle.js:6159:16
resolveLocals/<@http://localhost:3000/build/bundle.js:1034:15
forEach@http://localhost:3000/build/bundle.js:1776:11
resolveLocals@http://localhost:3000/build/bundle.js:1031:9
processQueue@http://localhost:3000/build/bundle.js:17824:28
scheduleProcessQueue/<@http://localhost:3000/build/bundle.js:17840:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/build/bundle.js:19123:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/build/bundle.js:18936:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/build/bundle.js:19231:13
bootstrapApply@http://localhost:3000/build/bundle.js:3202:9
invoke@http://localhost:3000/build/bundle.js:6159:16
bootstrap/doBootstrap@http://localhost:3000/build/bundle.js:3200:5
bootstrap@http://localhost:3000/build/bundle.js:3220:12
angularInit@http://localhost:3000/build/bundle.js:3105:5
[5]</</<@http://localhost:3000/build/bundle.js:33204:5
trigger@http://localhost:3000/build/bundle.js:4648:7
defaultHandlerWrapper@http://localhost:3000/build/bundle.js:4938:3
createEventHandler/eventHandler@http://localhost:3000/build/bundle.js:4926:9
1bundle.js:15361:18
consoleLog/<()bundle.js:15361
$ExceptionHandlerProvider/this.$get</<()bundle.js:11908
processQueue()bundle.js:17832
scheduleProcessQueue/<()bundle.js:17840
$RootScopeProvider/this.$get</Scope.prototype.$eval()bundle.js:19123
$RootScopeProvider/this.$get</Scope.prototype.$digest()bundle.js:18936
$RootScopeProvider/this.$get</Scope.prototype.$apply()bundle.js:19231
bootstrapApply()bundle.js:3202
invoke()bundle.js:6159
bootstrap/doBootstrap()bundle.js:3200
bootstrap()bundle.js:3220
angularInit()bundle.js:3105
[5]</</<()bundle.js:33204
trigger()bundle.js:4648
defaultHandlerWrapper()bundle.js:4938
createEventHandler/eventHandler()bundle.js:4926

**Comment by hgwood** [comment]
OK. Strange issue but I think I got it fixed. Could you try again? Sorry about this.

**Comment by christiandjak** [comment]
It is all good now!! Thanks!!!
